name: lsst-tests

on:
  push:
    branches:
      - master
  pull_request: null

jobs:
  lsst-tests:
    name: lsst-tests
    strategy:
      matrix:
        pyver: [3.8]

    runs-on: "ubuntu-latest"

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.pyver }}
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true

      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          conda install --quiet --yes mamba
          mamba install --quiet --yes --file requirements.txt
          mamba install --quiet --yes --file dev-requirements.txt
          mamba install -q -y stackvana=0 lsstdesc-weaklensingdeblending

          pip install --no-deps git+https://github.com/LSSTDESC/descwl-shear-sims.git
          pip install --no-deps git+https://github.com/LSSTDESC/descwl_coadd.git

          python -m pip install -e .

          git clone --branch u/erykoff/onlinecoadd https://github.com/lsst/pipe_tasks.git /tmp/pipe_tasks

      - name: temporarily use branch
        shell: bash -l {0}
        run: |
            env

            setup -j -r /tmp/pipe_tasks

            pushd /tmp/pipe_tasks
            # this might partly fail but that's ok
            scons || echo "ok scons fails"
            popd

            pip install --no-deps -e .

      - name: test ngmix w/ conda latest
        shell: bash -l {0}
        run: |
          pytest -vvs metadetect
